package Order_s;

import java.text.SimpleDateFormat;

import java.util.Calendar;

import java.util.Random;

import java.awt.Color;

/**

*

* @author Flipbell

*/

public class Orders extends javax.swing.JFrame {

Double firstnum;

Double secondnum;

Double result;

String operations;

double pizza = 4.0;

double pasta = 2.90;

double coke = 1.20;

double iTax = 7.50;

/**

* Creates new form Orders

*/

public Orders() {

initComponents();

getContentPane().setBackground(Color.WHITE);

}

/**

* This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.

*/

@SuppressWarnings("unchecked")

// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

private void initComponents() {

jPanel1 = new javax.swing.JPanel();

jSubTotal1 = new javax.swing.JTextField();

jSubTotal2 = new javax.swing.JTextField();

jSubTotal3 = new javax.swing.JTextField();

jLabel3 = new javax.swing.JLabel();

jUnitPrice1 = new javax.swing.JTextField();

jQTY2 = new javax.swing.JTextField();

jUnitPrice3 = new javax.swing.JTextField();

jLabel4 = new javax.swing.JLabel();

jQTY1 = new javax.swing.JTextField();

jUnitPrice2 = new javax.swing.JTextField();

jQTY3 = new javax.swing.JTextField();

jLabel5 = new javax.swing.JLabel();

jLabel6 = new javax.swing.JLabel();

jLabel7 = new javax.swing.JLabel();

jLabel8 = new javax.swing.JLabel();

jLabel9 = new javax.swing.JLabel();

jLabel10 = new javax.swing.JLabel();

jLabel11 = new javax.swing.JLabel();

jLabel12 = new javax.swing.JLabel();

jLabel13 = new javax.swing.JLabel();

jPhone = new javax.swing.JTextField();

jName = new javax.swing.JTextField();

jDate = new javax.swing.JTextField();

jTime = new javax.swing.JTextField();

jLabel1 = new javax.swing.JLabel();

jRefNo = new javax.swing.JLabel();

jLabel17 = new javax.swing.JLabel();

jPanel2 = new javax.swing.JPanel();

jButton21 = new javax.swing.JButton();

jButton22 = new javax.swing.JButton();

jButton23 = new javax.swing.JButton();

jButton24 = new javax.swing.JButton();

jLabel14 = new javax.swing.JLabel();

jLabel15 = new javax.swing.JLabel();

jLabel16 = new javax.swing.JLabel();

jOrderTotal = new javax.swing.JTextField();

jNetPrice = new javax.swing.JTextField();

jTaxPaid = new javax.swing.JTextField();

jOptionPane1 = new javax.swing.JTabbedPane();

jPanel3 = new javax.swing.JPanel();

jScrollPane1 = new javax.swing.JScrollPane();

jTextArea1 = new javax.swing.JTextArea();

jPanel4 = new javax.swing.JPanel();

jButton6 = new javax.swing.JButton();

jtxtDisplay = new javax.swing.JTextField();

jButton1 = new javax.swing.JButton();

jButton2 = new javax.swing.JButton();

jButton5 = new javax.swing.JButton();

jButton9 = new javax.swing.JButton();

jButton13 = new javax.swing.JButton();

jButton17 = new javax.swing.JButton();

jButton16 = new javax.swing.JButton();

jButton15 = new javax.swing.JButton();

jButton10 = new javax.swing.JButton();

jButton12 = new javax.swing.JButton();

jButton11 = new javax.swing.JButton();

jButton8 = new javax.swing.JButton();

jButton7 = new javax.swing.JButton();

jButton4 = new javax.swing.JButton();

jButton3 = new javax.swing.JButton();

jButton14 = new javax.swing.JButton();

jButton18 = new javax.swing.JButton();

jButton19 = new javax.swing.JButton();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

setSize(new java.awt.Dimension(2000, 100));

jPanel1.setBackground(new java.awt.Color(255, 255, 255));

jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

jSubTotal1.setEditable(false);

jSubTotal1.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jSubTotal1ActionPerformed(evt);

}

});

jSubTotal2.setEditable(false);

jSubTotal3.setEditable(false);

jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jLabel3.setText("Sub Total");

jUnitPrice1.setEditable(false);

jUnitPrice1.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jUnitPrice1ActionPerformed(evt);

}

});

jUnitPrice3.setEditable(false);

jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jLabel4.setText("QTY");

jQTY1.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jQTY1ActionPerformed(evt);

}

});

jUnitPrice2.setEditable(false);

jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jLabel5.setText("Unit Price");

jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jLabel6.setText("Item Type");

jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jLabel7.setText("Pizza");

jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jLabel8.setText("Pasta");

jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jLabel9.setText("Coke");

jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jLabel10.setText("Customer Telephone :");

jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jLabel11.setText("Cutomer Name : ");

jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jLabel12.setText("Order Time :");

jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jLabel13.setText("Order Date :");

jPhone.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jPhoneActionPerformed(evt);

}

});

jName.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jNameActionPerformed(evt);

}

});

jDate.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jDateActionPerformed(evt);

}

});

jTime.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jTimeActionPerformed(evt);

}

});

jLabel1.setFont(new java.awt.Font("Zian", 0, 24)); // NOI18N

jLabel1.setText("flipbell billing systems");

jRefNo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jRefNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jLabel17.setText("Order Number :");

javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);

jPanel1.setLayout(jPanel1Layout);

jPanel1Layout.setHorizontalGroup(

jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(jPanel1Layout.createSequentialGroup()

.addGap(38, 38, 38)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(jPanel1Layout.createSequentialGroup()

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)

.addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)

.addGroup(jPanel1Layout.createSequentialGroup()

.addComponent(jQTY1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

.addComponent(jUnitPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))

.addGroup(jPanel1Layout.createSequentialGroup()

.addComponent(jQTY3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

.addComponent(jUnitPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))

.addGroup(jPanel1Layout.createSequentialGroup()

.addComponent(jQTY2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

.addComponent(jUnitPrice2)))

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jSubTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

.addComponent(jSubTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)

.addComponent(jSubTotal1)))

.addGap(38, 38, 38))

.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)

.addGroup(jPanel1Layout.createSequentialGroup()

.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jLabel13))

.addGroup(jPanel1Layout.createSequentialGroup()

.addComponent(jLabel11)

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jLabel12)))

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jTime, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))

.addGap(23, 23, 23))

.addGroup(jPanel1Layout.createSequentialGroup()

.addComponent(jLabel10)

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)

.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))

.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()

.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()

.addComponent(jLabel4)

.addGap(194, 194, 194)

.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGap(101, 101, 101)

.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGap(121, 121, 121))

.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()

.addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addComponent(jRefNo, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGap(207, 207, 207))))

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(jPanel1Layout.createSequentialGroup()

.addGap(43, 43, 43)

.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)

.addContainerGap(751, Short.MAX_VALUE)))

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(jPanel1Layout.createSequentialGroup()

.addGap(208, 208, 208)

.addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)

.addContainerGap(433, Short.MAX_VALUE)))

);

jPanel1Layout.setVerticalGroup(

jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(jPanel1Layout.createSequentialGroup()

.addGap(41, 41, 41)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

.addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))

.addGap(53, 53, 53)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

.addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jTime, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))

.addGap(19, 19, 19))

.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()

.addContainerGap()

.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGap(18, 18, 18)

.addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGap(57, 57, 57)))

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)

.addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))

.addGap(33, 33, 33)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)

.addComponent(jRefNo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

.addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(jPanel1Layout.createSequentialGroup()

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

.addComponent(jSubTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jUnitPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jQTY1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))

.addGap(30, 30, 30))

.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()

.addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGap(24, 24, 24)))

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

.addComponent(jSubTotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jQTY2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jUnitPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))

.addGap(31, 31, 31)

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

.addComponent(jSubTotal3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jUnitPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jQTY3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))

.addGap(64, 64, 64))

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()

.addContainerGap(377, Short.MAX_VALUE)

.addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGap(274, 274, 274)))

.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(jPanel1Layout.createSequentialGroup()

.addGap(106, 106, 106)

.addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)

.addContainerGap(533, Short.MAX_VALUE)))

);

jPanel2.setBackground(new java.awt.Color(255, 255, 255));

jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

jButton21.setBackground(new java.awt.Color(0, 153, 255));

jButton21.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

jButton21.setText("Total");

jButton21.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton21ActionPerformed(evt);

}

});

jButton22.setBackground(new java.awt.Color(0, 153, 255));

jButton22.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

jButton22.setText("Reset");

jButton22.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton22ActionPerformed(evt);

}

});

jButton23.setBackground(new java.awt.Color(0, 153, 255));

jButton23.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

jButton23.setText("Display");

jButton23.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton23ActionPerformed(evt);

}

});

jButton24.setBackground(new java.awt.Color(204, 0, 0));

jButton24.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N

jButton24.setText("Exit");

jButton24.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton24ActionPerformed(evt);

}

});

jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jLabel14.setText("Tax Paid :");

jLabel15.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jLabel15.setText("Order Total :");

jLabel16.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N

jLabel16.setText("Net Paid :");

jOrderTotal.setEditable(false);

jOrderTotal.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jOrderTotalActionPerformed(evt);

}

});

jNetPrice.setEditable(false);

jNetPrice.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jNetPriceActionPerformed(evt);

}

});

jTaxPaid.setEditable(false);

jTaxPaid.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jTaxPaidActionPerformed(evt);

}

});

javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);

jPanel2.setLayout(jPanel2Layout);

jPanel2Layout.setHorizontalGroup(

jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()

.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jLabel16)

.addGroup(jPanel2Layout.createSequentialGroup()

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jLabel15)

.addComponent(jLabel14))

.addGap(97, 97, 97)

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jNetPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jTaxPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))))

.addGap(73, 73, 73)

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jButton22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jButton21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))

.addGap(61, 61, 61)

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))

.addGap(193, 193, 193))

);

jPanel2Layout.setVerticalGroup(

jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(jPanel2Layout.createSequentialGroup()

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(jPanel2Layout.createSequentialGroup()

.addContainerGap()

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

.addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

.addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jNetPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))

.addGroup(jPanel2Layout.createSequentialGroup()

.addGap(11, 11, 11)

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)

.addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jTaxPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGroup(jPanel2Layout.createSequentialGroup()

.addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))

.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

);

jOptionPane1.setBackground(new java.awt.Color(0, 102, 102));

jOptionPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

jOptionPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

jPanel3.setBackground(new java.awt.Color(255, 255, 255));

jTextArea1.setEditable(false);

jTextArea1.setColumns(20);

jTextArea1.setFont(new java.awt.Font("PMingLiU", 0, 24)); // NOI18N

jTextArea1.setRows(5);

jScrollPane1.setViewportView(jTextArea1);

javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);

jPanel3.setLayout(jPanel3Layout);

jPanel3Layout.setHorizontalGroup(

jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(jPanel3Layout.createSequentialGroup()

.addContainerGap()

.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)

.addContainerGap())

);

jPanel3Layout.setVerticalGroup(

jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(jPanel3Layout.createSequentialGroup()

.addContainerGap()

.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)

.addContainerGap())

);

jOptionPane1.addTab("Reciept", jPanel3);

jPanel4.setBackground(new java.awt.Color(255, 255, 255));

jButton6.setBackground(new java.awt.Color(150, 150, 150));

jButton6.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton6.setText("8");

jButton6.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton6ActionPerformed(evt);

}

});

jtxtDisplay.setEditable(false);

jtxtDisplay.setBackground(new java.awt.Color(120, 120, 120));

jtxtDisplay.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 48)); // NOI18N

jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

jtxtDisplay.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jtxtDisplayActionPerformed(evt);

}

});

jButton1.setBackground(new java.awt.Color(150, 150, 150));

jButton1.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton1.setText("C");

jButton1.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton1ActionPerformed(evt);

}

});

jButton2.setBackground(new java.awt.Color(150, 150, 150));

jButton2.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 18)); // NOI18N

jButton2.setText("-/+");

jButton2.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton2ActionPerformed(evt);

}

});

jButton5.setBackground(new java.awt.Color(150, 150, 150));

jButton5.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton5.setText("7");

jButton5.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton5ActionPerformed(evt);

}

});

jButton9.setBackground(new java.awt.Color(150, 150, 150));

jButton9.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton9.setText("4");

jButton9.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton9ActionPerformed(evt);

}

});

jButton13.setBackground(new java.awt.Color(150, 150, 150));

jButton13.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton13.setText("1");

jButton13.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton13ActionPerformed(evt);

}

});

jButton17.setBackground(new java.awt.Color(150, 150, 150));

jButton17.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton17.setText("0");

jButton17.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton17ActionPerformed(evt);

}

});

jButton16.setBackground(new java.awt.Color(243, 127, 39));

jButton16.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton16.setText("+");

jButton16.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton16ActionPerformed(evt);

}

});

jButton15.setBackground(new java.awt.Color(150, 150, 150));

jButton15.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton15.setText("3");

jButton15.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton15ActionPerformed(evt);

}

});

jButton10.setBackground(new java.awt.Color(150, 150, 150));

jButton10.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton10.setText("6");

jButton10.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton10ActionPerformed(evt);

}

});

jButton12.setBackground(new java.awt.Color(243, 127, 39));

jButton12.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton12.setText("-");

jButton12.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton12ActionPerformed(evt);

}

});

jButton11.setBackground(new java.awt.Color(150, 150, 150));

jButton11.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton11.setText("5");

jButton11.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton11ActionPerformed(evt);

}

});

jButton8.setBackground(new java.awt.Color(150, 150, 150));

jButton8.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton8.setText("9");

jButton8.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton8ActionPerformed(evt);

}

});

jButton7.setBackground(new java.awt.Color(243, 127, 39));

jButton7.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton7.setText("x");

jButton7.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton7ActionPerformed(evt);

}

});

jButton4.setBackground(new java.awt.Color(243, 127, 39));

jButton4.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton4.setText("÷");

jButton4.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton4ActionPerformed(evt);

}

});

jButton3.setBackground(new java.awt.Color(150, 150, 150));

jButton3.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton3.setText("%");

jButton3.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton3ActionPerformed(evt);

}

});

jButton14.setBackground(new java.awt.Color(150, 150, 150));

jButton14.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton14.setText("2");

jButton14.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton14ActionPerformed(evt);

}

});

jButton18.setBackground(new java.awt.Color(243, 127, 39));

jButton18.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton18.setText("=");

jButton18.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton18ActionPerformed(evt);

}

});

jButton19.setBackground(new java.awt.Color(150, 150, 150));

jButton19.setFont(new java.awt.Font("Apple SD Gothic Neo", 0, 36)); // NOI18N

jButton19.setText(".");

jButton19.addActionListener(new java.awt.event.ActionListener() {

public void actionPerformed(java.awt.event.ActionEvent evt) {

jButton19ActionPerformed(evt);

}

});

javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);

jPanel4.setLayout(jPanel4Layout);

jPanel4Layout.setHorizontalGroup(

jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(jPanel4Layout.createSequentialGroup()

.addGap(14, 14, 14)

.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()

.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

.addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))

.addGap(28, 28, 28)

.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)

.addGroup(jPanel4Layout.createSequentialGroup()

.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

.addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)

.addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

.addGroup(jPanel4Layout.createSequentialGroup()

.addGap(7, 7, 7)

.addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))

.addGroup(jPanel4Layout.createSequentialGroup()

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))

.addGap(10, 10, 10))

.addGroup(jPanel4Layout.createSequentialGroup()

.addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))

.addGroup(jPanel4Layout.createSequentialGroup()

.addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))

.addGap(18, 18, 18)

.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addGroup(jPanel4Layout.createSequentialGroup()

.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))

.addGap(0, 0, Short.MAX_VALUE)))

.addContainerGap())

.addGroup(jPanel4Layout.createSequentialGroup()

.addContainerGap()

.addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)

.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

);

jPanel4Layout.setVerticalGroup(

jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(jPanel4Layout.createSequentialGroup()

.addContainerGap()

.addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGap(81, 81, 81)

.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(jPanel4Layout.createSequentialGroup()

.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)

.addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)

.addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

.addGap(10, 10, 10)

.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()

.addGap(0, 0, Short.MAX_VALUE)

.addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))

.addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(jPanel4Layout.createSequentialGroup()

.addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGap(0, 0, Short.MAX_VALUE))

.addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

.addGap(18, 18, 18)

.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

.addGap(18, 18, 18)

.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)

.addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)

.addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

.addGap(31, 31, 31))

.addGroup(jPanel4Layout.createSequentialGroup()

.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)

.addGap(0, 0, Short.MAX_VALUE))))

);

jOptionPane1.addTab("Calculator", jPanel4);

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());

getContentPane().setLayout(layout);

layout.setHorizontalGroup(

layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(layout.createSequentialGroup()

.addGap(15, 15, 15)

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(layout.createSequentialGroup()

.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)

.addGap(18, 18, 18)

.addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))

.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

.addContainerGap())

);

layout.setVerticalGroup(

layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()

.addContainerGap()

.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

.addComponent(jOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE))

.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)

.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)

.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))

);

pack();

}// </editor-fold>//GEN-END:initComponents

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

String Enternumber = jtxtDisplay.getText() + jButton6.getText();

jtxtDisplay.setText (Enternumber);

}//GEN-LAST:event_jButton6ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

String Enternumber = jtxtDisplay.getText() + jButton13.getText();

jtxtDisplay.setText ("");

}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

Double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));

ops = ops * (-1);

jtxtDisplay.setText(String.valueOf(ops));

}//GEN-LAST:event_jButton2ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

String Enternumber = jtxtDisplay.getText() + jButton5.getText();

jtxtDisplay.setText (Enternumber);

}//GEN-LAST:event_jButton5ActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

String Enternumber = jtxtDisplay.getText() + jButton9.getText();

jtxtDisplay.setText (Enternumber);

}//GEN-LAST:event_jButton9ActionPerformed

private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

String Enternumber = jtxtDisplay.getText() + jButton13.getText();

jtxtDisplay.setText (Enternumber);

}//GEN-LAST:event_jButton13ActionPerformed

private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

String Enternumber = jtxtDisplay.getText() + jButton17.getText();

jtxtDisplay.setText (Enternumber);

}//GEN-LAST:event_jButton17ActionPerformed

private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

String answer;

secondnum = Double.parseDouble(jtxtDisplay.getText());

if (operations == "+")

{

result = firstnum + secondnum;

answer = String.format("%.0f",result);

jtxtDisplay.setText(answer);

}

else if (operations == "-")

{

result = firstnum - secondnum;

answer = String.format("%.0f",result);

jtxtDisplay.setText(answer);

}

else if (operations == "*")

{

result = firstnum * secondnum;

answer = String.format("%.0f",result);

jtxtDisplay.setText(answer);

}

else if (operations == "/")

{

result = firstnum / secondnum;

answer = String.format("%.0f",result);

jtxtDisplay.setText(answer);

}

else if (operations == "%")

{

result = firstnum % secondnum;

answer = String.format("%.0f",result);

jtxtDisplay.setText(answer);

}

}//GEN-LAST:event_jButton18ActionPerformed

private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

firstnum = Double.parseDouble(jtxtDisplay.getText());

jtxtDisplay.setText("");

operations = "+";

}//GEN-LAST:event_jButton16ActionPerformed

private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed

String Enternumber = jtxtDisplay.getText() + jButton19.getText();

jtxtDisplay.setText (Enternumber);

}//GEN-LAST:event_jButton19ActionPerformed

private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

String Enternumber = jtxtDisplay.getText() + jButton15.getText();

jtxtDisplay.setText (Enternumber);

}//GEN-LAST:event_jButton15ActionPerformed

private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

String Enternumber = jtxtDisplay.getText() + jButton10.getText();

jtxtDisplay.setText (Enternumber);

}//GEN-LAST:event_jButton10ActionPerformed

private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

firstnum = Double.parseDouble(jtxtDisplay.getText());

jtxtDisplay.setText("");

operations = "-";

}//GEN-LAST:event_jButton12ActionPerformed

private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

String Enternumber = jtxtDisplay.getText() + jButton11.getText();

jtxtDisplay.setText (Enternumber);

}//GEN-LAST:event_jButton11ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

String Enternumber = jtxtDisplay.getText() + jButton8.getText();

jtxtDisplay.setText (Enternumber);

}//GEN-LAST:event_jButton8ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

firstnum = Double.parseDouble(jtxtDisplay.getText());

jtxtDisplay.setText("");

operations = "*";

}//GEN-LAST:event_jButton7ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

firstnum = Double.parseDouble(jtxtDisplay.getText());

jtxtDisplay.setText("");

operations = "/";

}//GEN-LAST:event_jButton4ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

firstnum = Double.parseDouble(jtxtDisplay.getText());

jtxtDisplay.setText("");

operations = "%";

}//GEN-LAST:event_jButton3ActionPerformed

private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

String Enternumber = jtxtDisplay.getText() + jButton14.getText();

jtxtDisplay.setText (Enternumber);

}//GEN-LAST:event_jButton14ActionPerformed

private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed

// TODO add your handling code here:

}//GEN-LAST:event_jtxtDisplayActionPerformed

private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed

jTextArea1.setText(null);

jDate.setText(null);

jTime.setText(null);

jQTY1.setText(null);

jQTY2.setText(null);

jQTY3.setText(null);

jUnitPrice1.setText(null);

jUnitPrice2.setText(null);

jUnitPrice3.setText(null);

jSubTotal1.setText(null);

jSubTotal2.setText(null);

jSubTotal3.setText(null);

jOrderTotal.setText(null);

jTaxPaid.setText(null);

jNetPrice.setText(null);

jPhone.setText(null);

jName.setText(null);

}//GEN-LAST:event_jButton22ActionPerformed

private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed

System.exit(0);

}//GEN-LAST:event_jButton24ActionPerformed

private void jSubTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubTotal1ActionPerformed

// TODO add your handling code here:

}//GEN-LAST:event_jSubTotal1ActionPerformed

private void jUnitPrice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUnitPrice1ActionPerformed

// TODO add your handling code here:

}//GEN-LAST:event_jUnitPrice1ActionPerformed

private void jQTY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQTY1ActionPerformed

// TODO add your handling code here:

}//GEN-LAST:event_jQTY1ActionPerformed

private void jPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhoneActionPerformed

// TODO add your handling code here:

}//GEN-LAST:event_jPhoneActionPerformed

private void jNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameActionPerformed

// TODO add your handling code here:

}//GEN-LAST:event_jNameActionPerformed

private void jDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateActionPerformed

// TODO add your handling code here:

}//GEN-LAST:event_jDateActionPerformed

private void jTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTimeActionPerformed

// TODO add your handling code here:

}//GEN-LAST:event_jTimeActionPerformed

private void jOrderTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOrderTotalActionPerformed

// TODO add your handling code here:

}//GEN-LAST:event_jOrderTotalActionPerformed

private void jNetPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNetPriceActionPerformed

// TODO add your handling code here:

}//GEN-LAST:event_jNetPriceActionPerformed

private void jTaxPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTaxPaidActionPerformed

// TODO add your handling code here:

}//GEN-LAST:event_jTaxPaidActionPerformed

private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed

double QTY1 = Double.parseDouble(jQTY1.getText());

double QTY2 = Double.parseDouble(jQTY2.getText());

double QTY3 = Double.parseDouble(jQTY3.getText());

double total, subTotal, Addup,vTax, purchase1, purchase2, purchase3;

String white_wine = String.format("£%.2f", pizza);

jUnitPrice1.setText(white_wine);

String red_wine = String.format("£%.2f", pasta);

jUnitPrice2.setText(red_wine);

String other_wine = String.format("£%.2f", coke);

jUnitPrice3.setText(other_wine);

purchase1 = QTY1 * pizza;

purchase2 = QTY2 * pasta;

purchase3 = QTY3 * coke;

String sub1 = String.format("£%.2f", purchase1);

jSubTotal1.setText(sub1);

String sub2 = String.format("£%.2f", purchase2);

jSubTotal2.setText(sub2);

String sub3 = String.format("£%.2f", purchase3);

jSubTotal3.setText(sub3);

//==========================Tax======================================

subTotal = purchase1 + purchase2 + purchase3;

vTax = (subTotal * iTax)/100;

String subTax = String.format("£%.2f", vTax);

jTaxPaid.setText(subTax);

//=======================Total Price================================

String subTotalAll = String.format("£%.2f", subTotal);

jOrderTotal.setText(subTotalAll);

//=======================Net Price================================

Addup = subTotal + vTax;

String TotalAll = String.format("£%.2f", Addup);

jNetPrice.setText(TotalAll);

//============================Date and time======================================

Calendar timer = Calendar.getInstance();

timer.getTime();

SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");

jTime.setText(tTime.format(timer.getTime()));

SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");

jDate.setText(Tdate.format(timer.getTime()));

//=====================Order Number======================================================

int num1;

String OrderRefNo = "";

num1 = 1325 + (int) (Math.random()*4238);

OrderRefNo += num1 + 1325;

jRefNo.setText(OrderRefNo);

}//GEN-LAST:event_jButton21ActionPerformed

private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed

String OrderRefNo =jRefNo.getText();

String iDate = jDate.getText();

String iTime = jTime.getText();

double QTY1 = Double.parseDouble(jQTY1.getText());

double QTY2 = Double.parseDouble(jQTY2.getText());

double QTY3 = Double.parseDouble(jQTY3.getText());

double QTY4 = (QTY1 + QTY2 + QTY3);

jTextArea1.append("\tFlipbell Shopping Store\n\n\n" + "Number of pizza\t\t"

+QTY1 + "\nNumber of pasta\t\t"+QTY2 + "\nNumber of coke\t"

+ +QTY3 + "\n" + "Total number of items\t" + QTY4 +

"\n\n" + "Order Ref No\t\t" + OrderRefNo + "\n" +"Date\t\t" + iDate + "\n" +"Time\t" + iTime + "\n\tThanks for Shopping with us!");

}//GEN-LAST:event_jButton23ActionPerformed

/**

* @param args the command line arguments

*/

public static void main(String args[]) {

/* Set the Nimbus look and feel */

//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.

* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html

*/

try {

for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

if ("Nimbus".equals(info.getName())) {

javax.swing.UIManager.setLookAndFeel(info.getClassName());

break;

}

}

} catch (ClassNotFoundException ex) {

java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {

java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {

java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {

java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);

}

//</editor-fold>

/* Create and display the form */

java.awt.EventQueue.invokeLater(new Runnable() {

public void run() {

new Orders().setVisible(true);

}

});

}

// Variables declaration - do not modify//GEN-BEGIN:variables

private javax.swing.JButton jButton1;

private javax.swing.JButton jButton10;

private javax.swing.JButton jButton11;

private javax.swing.JButton jButton12;

private javax.swing.JButton jButton13;

private javax.swing.JButton jButton14;

private javax.swing.JButton jButton15;

private javax.swing.JButton jButton16;

private javax.swing.JButton jButton17;

private javax.swing.JButton jButton18;

private javax.swing.JButton jButton19;

private javax.swing.JButton jButton2;

private javax.swing.JButton jButton21;

private javax.swing.JButton jButton22;

private javax.swing.JButton jButton23;

private javax.swing.JButton jButton24;

private javax.swing.JButton jButton3;

private javax.swing.JButton jButton4;

private javax.swing.JButton jButton5;

private javax.swing.JButton jButton6;

private javax.swing.JButton jButton7;

private javax.swing.JButton jButton8;

private javax.swing.JButton jButton9;

private javax.swing.JTextField jDate;

private javax.swing.JLabel jLabel1;

private javax.swing.JLabel jLabel10;

private javax.swing.JLabel jLabel11;

private javax.swing.JLabel jLabel12;

private javax.swing.JLabel jLabel13;

private javax.swing.JLabel jLabel14;

private javax.swing.JLabel jLabel15;

private javax.swing.JLabel jLabel16;

private javax.swing.JLabel jLabel17;

private javax.swing.JLabel jLabel3;

private javax.swing.JLabel jLabel4;

private javax.swing.JLabel jLabel5;

private javax.swing.JLabel jLabel6;

private javax.swing.JLabel jLabel7;

private javax.swing.JLabel jLabel8;

private javax.swing.JLabel jLabel9;

private javax.swing.JTextField jName;

private javax.swing.JTextField jNetPrice;

private javax.swing.JTabbedPane jOptionPane1;

private javax.swing.JTextField jOrderTotal;

private javax.swing.JPanel jPanel1;

private javax.swing.JPanel jPanel2;

private javax.swing.JPanel jPanel3;

private javax.swing.JPanel jPanel4;

private javax.swing.JTextField jPhone;

private javax.swing.JTextField jQTY1;

private javax.swing.JTextField jQTY2;

private javax.swing.JTextField jQTY3;

private javax.swing.JLabel jRefNo;

private javax.swing.JScrollPane jScrollPane1;

private javax.swing.JTextField jSubTotal1;

private javax.swing.JTextField jSubTotal2;

private javax.swing.JTextField jSubTotal3;

private javax.swing.JTextField jTaxPaid;

private javax.swing.JTextArea jTextArea1;

private javax.swing.JTextField jTime;

private javax.swing.JTextField jUnitPrice1;

private javax.swing.JTextField jUnitPrice2;

private javax.swing.JTextField jUnitPrice3;

private javax.swing.JTextField jtxtDisplay;

// End of variables declaration//GEN-END:variables

}